function sim_UI

% Create UI Figure
figure_width = 560;
figure_height = 420;
border_buffer = 10;
app = uifigure;
app.Name = "Simulator UI";
app.Position(3:4) = [figure_width figure_height];
app.Resize = "off";

% Try to load previous settings
if ~exist("Saved Data\\UI Settings", 'dir')
    mkdir("Saved Data\\UI Settings")
end
try
    loaded_settings = load("Saved Data\\UI Settings\\master_settings.mat");
catch
end

% Define needed vectors
var_list = ["EbN0_db","M_ary","select_mod","sbcar_spacing","Fc","v_vel","N_tsyms","M_sbcars","q","filter","rolloff"];
def_names = strcat("def_",var_list);
var_defaults = {18,4,"MPSK",15e3,4e9,500,16,64,8,"rect",1};
def_string = "";
for i = 1:length(var_list)
    % if i > 1
    def_string = def_string + ", ";
    % end
    def_string = def_string + """" + def_names(i) + """";
end
def_string = def_string + "";

% Simulation settings
sim_width = 160;
sim_length = 260;
sim_panel = uipanel(app,"Position",[border_buffer figure_height-sim_length-border_buffer sim_width sim_length],"Title","Simulation variables");
v1_lbl = uilabel(sim_panel, ...
    'Text', 'Select primary variable:', ...
    'Position', [border_buffer, border_buffer+25*8, sim_panel.Position(3)-2*border_buffer, 22]);
v1 = uidropdown(sim_panel,...
    "Position",[border_buffer border_buffer+25*7 sim_panel.Position(3)-2*border_buffer 22],...
    "Items",var_list);
v1_range = uieditfield(sim_panel,...
    "Text",...
    "Position",[border_buffer border_buffer+25*6 sim_panel.Position(3)-2*border_buffer 22],...
    "Value","Primary var range");
v2_lbl = uilabel(sim_panel, ...
    'Text', 'Select primary variable:', ...
    'Position', [border_buffer, border_buffer+25*5, sim_panel.Position(3)-2*border_buffer, 22]);
v2 = uidropdown(sim_panel,...
    "Position",[border_buffer border_buffer+25*4 sim_panel.Position(3)-2*border_buffer 22],...
    "Items",["NA", var_list]);
v2_range = uieditfield(sim_panel,...
    "Text",...
    "Position",[border_buffer border_buffer+25*3 sim_panel.Position(3)-2*border_buffer 22],...
    "Value","Secondary var range");
x_lbl = uilabel(sim_panel, ...
    'Text', 'Select sweep variable:', ...
    'Position', [border_buffer, border_buffer+25*2, sim_panel.Position(3)-2*border_buffer, 22]);
x = uidropdown(sim_panel,...
    "Position",[border_buffer border_buffer+25 sim_panel.Position(3)-2*border_buffer 22],...
    "Items",var_list);
x_low = uieditfield(sim_panel,...
    "Text",...
    "Position",[border_buffer border_buffer (sim_panel.Position(3)-2*border_buffer)/3 22],...
    "Value","Min x");
x_step = uieditfield(sim_panel,...
    "Text",...
    "Position",[border_buffer+x_low.Position(3) border_buffer x_low.Position(3) 22],...
    "Value","Step");
x_high = uieditfield(sim_panel,...
    "Text",...
    "Position",[border_buffer+x_low.Position(3)*2 border_buffer x_low.Position(3) 22],...
    "Value","Max x");
sim_panel.Scrollable = "on";

% Figure settings
fig_width = sim_width;
fig_length = 100+3*border_buffer;
% fig_panel = uipanel(fig,"Position",[border_buffer border_buffer sim_panel.Position(3) fig.Position(4)-sim_panel.Position(4)-3*border_buffer],"Title","Figure settings");
fig_panel = uipanel(app,"Position",[border_buffer sim_panel.Position(2)-border_buffer-fig_length fig_width fig_length],"Title","Figure settings");
error_lbl = uilabel(fig_panel, ...
    'Text', 'Max errors per sim:', ...
    'Position', [border_buffer, border_buffer+3*25, fig_panel.Position(3)-2*border_buffer, 22]);
max_errors = uieditfield(fig_panel,...
    "Text",...
    "Position",[border_buffer border_buffer+2*25 fig_panel.Position(3)-2*border_buffer 22],...
    "Value","Inf");
frame_lbl = uilabel(fig_panel, ...
    'Text', 'Max frames per sim:', ...
    'Position', [border_buffer, border_buffer+1*25, fig_panel.Position(3)-2*border_buffer, 22]);
max_frames = uieditfield(fig_panel,...
    "Text",...
    "Position",[border_buffer border_buffer fig_panel.Position(3)-2*border_buffer 22],...
    "Value","500");

% Default settings
def_width = 200;
def_length = figure_height-2*border_buffer;
def_box_width = 80;
def_panel = uipanel(app,"Position",[figure_width-def_width-border_buffer (figure_height-def_length)-border_buffer def_width def_length],"Title","Parameter defaults");
for i = 1:length(var_list)
    eval(def_names(i) + "_lbl = uilabel(def_panel, 'Text', var_list(length(var_list)-i+1) + ':', 'Position', [border_buffer, " + (border_buffer+(i-1)*25) + ", "+((def_width/2)-2*border_buffer)+", 22]);")
    eval(def_names(i) + " = uieditfield(def_panel,""Text"",""Position"",["+def_names(i)+"_lbl.Position(3)+" + 2*border_buffer + ", " + (border_buffer+(i-1)*25) + ", "+def_names(i)+"_lbl.Position(3), 22],""Value"",string(var_defaults{i}));")
end
def_panel.Scrollable = "on";

% Create run button
run_btn = uibutton(app, 'push', ...
    'Text', 'Run', ...
    'Position', [sim_width+border_buffer*2, fig_panel.Position(2), 100, 30], ...
    'ButtonPushedFcn', @(run_btn,event) main_uifun(settings_obj,def_names,defaults_obj,var_list));


eval("save(""Saved Data\\UI Settings\\master_settings.mat"""+def_string+");")

end


% Save settings externally
function update_settings(src,event)
settings_obj = {v1.Value,v1_range.Value,v2.Value,v2_range.Value,x.Value,x_low.Value,x_step.Value,x_high.Value,max_errors.Value,max_frames.Value};
eval(def_string);
end
